sotw:
  # This value is changed by /sotw in game, this is the serialized value.
  enabled: false
  cooldowned-commands:
    island:
      # This will search for the command and find all of it's aliases so it will also block those, this will also block the pluginname:command shortcuts automatically.
      use-bukkit-commandmap: false
      # This will check for String#startsWith instead of String#equalsIgnoreCase
      starts-with: true
      commands:
        - 'island'
        - 'islands'
        - 'is'
      in-cooldown-message: '&cUnable to execute {command} because youre on cooldown for another {time} seconds'
      cooldown-time:
        donator:
          enabled: true
          permission: 'some.donator.permission.use'
          # Time in milliseconds
          time:
            ranged:
              enabled: false
              min: 0
              max: 0
            # The time doesn't change at all. Set static to 0 if you don't want to use it, although the ranged time must be above 0 or there will be no delay.
            static: 60000
        regular:
          time:
            # Ranged time where it will be random at the time of joining
            ranged:
              enabled: true
              min: 60000
              max: 120000
            static: 0